AWSTemplateFormatVersion: '2010-09-09'

Description: One IAM user for the home-assistant-helper docker and one IAM user for the home-assistant-helper host

Metadata:
  Author:
    - Teemo Dai

Parameters:
  MahicneName:
    Type: String
    Description: Name of the machine to create the IAM user for
  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID
    Default: Z06958611JDYVCG41K93R
  SecondLevelDomainName:
    Type: String
    Description: SLD, the domain name you registered (e.g., "example" in "example.com")
    Default: the-alchemist.link

Resources:

  # for the docker to update R53 records and S3
  DockerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${MahicneName}-docker-user"
      Policies:
        - PolicyName: AllowUpdateR53andS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - route53:GetHostedZone
                Resource: '*'

              - Effect: Allow
                Action: route53:ChangeResourceRecordSets
                Resource: !Sub arn:aws:route53:::hostedzone/${HostedZoneId}
                Condition:
                  StringLike:
                    "route53:ChangeResourceRecordSetsNormalizedRecordNames":
                      - !Sub "${MahicneName}.${SecondLevelDomainName}"
                    "route53:ChangeResourceRecordSetsActions":
                      - CREATE
                      - UPSERT

              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: arn:aws:s3:::the-alchemist-home-assistant
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub arn:aws:s3:::the-alchemist-home-assistant/${MahicneName}/backup/*

  # for the host to fetch the docker image from ECR
  HostUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${MahicneName}-host-user"
      Policies:
        - PolicyName: AllowFetchECRImage${MahicneName}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ECRAuthToken
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"

              - Sid: AllowPullFromSpecificRepo
                Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: arn:aws:ecr:ap-southeast-2:654654455942:repository/home-assistant-helper-${MahicneName}
