AWSTemplateFormatVersion: '2010-09-09'

Description: Resources for a local Home Assistant OS e.g. my raspberry pi

Metadata:
  Author:
    - Teemo Dai

Parameters:
  MachineNickName:
    Type: String
    Description: Nick name of the machine
  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID
    Default: Z06958611JDYVCG41K93R
  SecondLevelDomainName:
    Type: String
    Description: SLD, the domain name you registered
    Default: the-alchemist.link

Resources:

  HomeAssistantUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "home-assistant-user-${MachineNickName}"
      Policies:
        - PolicyName: AllowUpdateR53andS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - route53:ListHostedZones
                  - route53:GetChange
                Resource: "*"
              - Effect: Allow
                Action:
                  - route53:GetHostedZone
                Resource: !Sub arn:aws:route53:::hostedzone/${HostedZoneId}

              - Effect: Allow
                Action: route53:ChangeResourceRecordSets
                Resource: !Sub arn:aws:route53:::hostedzone/${HostedZoneId}
                Condition:
                  StringLike:
                    "route53:ChangeResourceRecordSetsNormalizedRecordNames":
                      - !Sub "${MachineNickName}.${SecondLevelDomainName}"
                      - !Sub "_acme-challenge.${MachineNickName}.${SecondLevelDomainName}"
                    "route53:ChangeResourceRecordSetsActions":
                      - CREATE
                      - UPSERT

              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: arn:aws:s3:::the-alchemist-home-assistant
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub arn:aws:s3:::the-alchemist-home-assistant/${MachineNickName}/*

              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"

              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: !Sub arn:aws:ecr:ap-southeast-2:654654455942:repository/home-assistant-helper-${MachineNickName}
              
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: arn:aws:ssm:ap-southeast-2:654654455942:parameter/github/pat/home-assistant-config

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "home-assistant-helper-${MachineNickName}"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
