name: ci-pipeline

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-pipeline.yaml'
      - 'cloudformation/stack-for-one-home.yaml'
      - 'docker/**'

jobs:
  lint:
    name: cfnLint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cfn-lint
        run: |
          pip install cfn-lint

      - name: Lint CloudFormation template
        run: |
          cfn-lint cloudformation/stack-for-one-home.yaml

  deploy:
    name: DeployCloudformation
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine-nick-name: [home] # You can add more machine names here, e.g., [home1, home2, machine3, machine4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: deploy-cfn-home-assistant-${{ matrix.machine-nick-name }}
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: home-assistant-${{ matrix.machine-nick-name }}
          template: cloudformation/stack-for-one-home.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >
            MachineNickName=${{ matrix.machine-nick-name }}
          capabilities: CAPABILITY_NAMED_IAM

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push home-assistant-helper-${{ matrix.machine-nick-name }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: 654654455942.dkr.ecr.ap-southeast-2.amazonaws.com/home-assistant-helper-${{ matrix.machine-nick-name }}:latest
          build-args: |
            GITHUB_TOKEN="${{ secrets.HOME_ASSISTANCE_CONFIG_GITHUB_PAT }}" \
            MACHINE_NICKNAME="${{ matrix.machine-nick-name }}"
