name: ci-pipeline

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-pipeline.yaml'
      - 'cloudformation/iam-users.yaml'
      - 'docker/**'

jobs:
  lint:
    name: cfnLint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cfn-lint
        run: |
          pip install cfn-lint

      - name: Lint CloudFormation template
        run: |
          cfn-lint cloudformation/iam-users.yaml

  deploy:
    name: DeployCloudformation
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine-nick-name: [home] # You can add more machine names here, e.g., [home1, home2, machine3, machine4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: deploy-cfn-home-assistant-${{ matrix.machine-nick-name }}-iam-users
        id: iam-users
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: home-assistant-${{ matrix.machine-nick-name }}-iam-users
          template: cloudformation/iam-users.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >
            MachineNickName=${{ matrix.machine-nick-name }}
          capabilities: CAPABILITY_NAMED_IAM

# next:
# github needs to get the aws credentials for the docker user
# then build the docker image
# --build-arg MACHINE_NICKNAME=home --build-arg GITHUB_TOKEN=github-token-for-home-assistant-config

# then push the docker image to ECR

